### ISSUE TITLE
AttributeError: Namespace object has not attribute 'batch'

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#1]
Hi, i have followed your instructions and wanna run the train.py file. But I am getting this error would you please give me any suggestions. thanks in advance

**Comment by tiangexiang** [comment]
Hi, sorry for the glitch. It is because of the inconsistency between 'batch' and 'batch_size'. I have now fixed the issue and updated repo, it should work fine now, please give another try again :)
