### ISSUE TITLE
whats the Querry for the Predicted Segmentation Mask?

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#4]
thank you for you modifications

i have change the line of 46 " x_train, y_train, batch_size=args.batch_size" with " x_train, y_train, batch_size=args.batch" and then also make modification in line 120 "result = model.evaluate(x,batch_size=args.batch)" but i am getting the namespace error. Yes i want to get the predicted Segmentation masks.

**Comment by tiangexiang** [comment]
Hi, the code has been updated to support saving of segmentation results (masks), please follow the instructions in README.md and try again:)

You don't need to change any code at this point. If there is still a problem, please let me know! Thanks
