### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#8]
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main(args, CORE)
  File "main.py", line 48, in main
    CORE.train(args)
  File "/home/ali/Ali_Bionet/keras_version/utils.py", line 37, in train
    input_shape = x_train[0].shape
TypeError: 'NoneType' object is not subscriptable

**Comment by AliMedVisionTech** [comment]
Can you please give me any suggstions ?

**Comment by tiangexiang** [comment]
Hi, this is because the loading of the MoNuSeg training set failed. Can you double-check the path to the dataset is correct and the dataset is identical to the ones provided in this repo?
