### ISSUE TITLE
Thanks for your outstanding work. Do you have any guidance how to get shapes of layers for visualization. I have tried different method in keras but facing some trouble, Thanks in advance 

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#9]
AttributeError: Layer conv2d_3 has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.

**Comment by AliMedVisionTech** [comment]
Do you have any wechat id ? wanna share with you my code ?

**Comment by AliMedVisionTech** [comment]
您有任何微信ID吗？ 想与您分享我的代码吗？

**Comment by tiangexiang** [comment]
Hi, by 'shapes of layers', do you mean the feature map size, in_channel num, and out_channel num at each layer? If this is the case, you can simply print(model.summary()) somewhere after the model instance has been created. Also, the shapes are supposed to be identical to the ones outlined in the paper Figure 1. 

As for your encountered issue, the error means that layer conv2d_3 has more than one output, and you can only get one of them at a time. Use something like model.get_layer('conv2d_3').get_output_at(0) gives you the first output of this layer.

**Comment by AliMedVisionTech** [comment]
thanks for your reply

**Comment by AliMedVisionTech** [comment]
我实际上是在尝试获取特征图的可视化，您对我如何获得它有任何建议吗？
